version: "3"
services:
  web:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel/public:/var/www/html/public
    depends_on:
      - app
  app:
    build: .
    tty: true
    volumes:
      - ./laravel:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: photo-app
    volumes:
      - ./db:/var/lib/mysql
